### PR TITLE
added game-rules

### PR DESCRIPTION
**Pull request by ttravers17**
I added what I believe to be the correct rules of the game.

### CODE REVIEW

**Comment by stephantabor** [comment]
I'll let Dick review these...

**Comment by RWTreichel** [comment]
Dang you picked it up really fast, looks good!

**Comment by ttravers17** [comment]
Dude im just happy to not have to do a blog.

**Comment by RWTreichel** [comment]
Haha I feel ya.

**Comment by stephantabor** [comment]
Alright I'm merging it then

**Pull request merged**
